//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.TeamService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeamService.ICreateEditeTeamContract")]
    public interface ICreateEditeTeamContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/CreateNewTeam", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/CreateNewTeamResponse")]
        void CreateNewTeam(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO newTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/CreateNewTeam", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/CreateNewTeamResponse")]
        System.Threading.Tasks.Task CreateNewTeamAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO newTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/EditTeam", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/EditTeamResponse")]
        void EditTeam([System.ServiceModel.MessageParameterAttribute(Name="editTeam")] WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO editTeam1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/EditTeam", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/EditTeamResponse")]
        System.Threading.Tasks.Task EditTeamAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO editTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/DeleteTeam", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/DeleteTeamResponse")]
        void DeleteTeam([System.ServiceModel.MessageParameterAttribute(Name="deleteTeam")] WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO deleteTeam1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/DeleteTeam", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/DeleteTeamResponse")]
        System.Threading.Tasks.Task DeleteTeamAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO deleteTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/GetAllUsersTeams", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/GetAllUsersTeamsResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[] GetAllUsersTeams(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/GetAllUsersTeams", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/GetAllUsersTeamsResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[]> GetAllUsersTeamsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/GetAllTeams", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/GetAllTeamsResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[] GetAllTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeTeamContract/GetAllTeams", ReplyAction="http://tempuri.org/ICreateEditeTeamContract/GetAllTeamsResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[]> GetAllTeamsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEditeTeamContractChannel : PresentationLayer.TeamService.ICreateEditeTeamContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEditeTeamContractClient : System.ServiceModel.ClientBase<PresentationLayer.TeamService.ICreateEditeTeamContract>, PresentationLayer.TeamService.ICreateEditeTeamContract {
        
        public CreateEditeTeamContractClient() {
        }
        
        public CreateEditeTeamContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEditeTeamContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeTeamContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeTeamContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateNewTeam(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO newTeam) {
            base.Channel.CreateNewTeam(newTeam);
        }
        
        public System.Threading.Tasks.Task CreateNewTeamAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO newTeam) {
            return base.Channel.CreateNewTeamAsync(newTeam);
        }
        
        public void EditTeam(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO editTeam1) {
            base.Channel.EditTeam(editTeam1);
        }
        
        public System.Threading.Tasks.Task EditTeamAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO editTeam) {
            return base.Channel.EditTeamAsync(editTeam);
        }
        
        public void DeleteTeam(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO deleteTeam1) {
            base.Channel.DeleteTeam(deleteTeam1);
        }
        
        public System.Threading.Tasks.Task DeleteTeamAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO deleteTeam) {
            return base.Channel.DeleteTeamAsync(deleteTeam);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[] GetAllUsersTeams(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO user) {
            return base.Channel.GetAllUsersTeams(user);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[]> GetAllUsersTeamsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO user) {
            return base.Channel.GetAllUsersTeamsAsync(user);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[] GetAllTeams() {
            return base.Channel.GetAllTeams();
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO[]> GetAllTeamsAsync() {
            return base.Channel.GetAllTeamsAsync();
        }
    }
}
