//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.ProfileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileService.ICreateEditeProfileContract")]
    public interface ICreateEditeProfileContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/AddProfile", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/AddProfileResponse")]
        void AddProfile(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO newProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/AddProfile", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/AddProfileResponse")]
        System.Threading.Tasks.Task AddProfileAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO newProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/EditeProfile", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/EditeProfileResponse")]
        void EditeProfile([System.ServiceModel.MessageParameterAttribute(Name="editeProfile")] WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO editeProfile1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/EditeProfile", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/EditeProfileResponse")]
        System.Threading.Tasks.Task EditeProfileAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO editeProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/GetProfileDTO", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/GetProfileDTOResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO GetProfileDTO(DataAccessLayer.cs.Models.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/GetProfileDTO", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/GetProfileDTOResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO> GetProfileDTOAsync(DataAccessLayer.cs.Models.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/GetProfile", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/GetProfileResponse")]
        DataAccessLayer.cs.Models.Profile GetProfile(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO profileDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeProfileContract/GetProfile", ReplyAction="http://tempuri.org/ICreateEditeProfileContract/GetProfileResponse")]
        System.Threading.Tasks.Task<DataAccessLayer.cs.Models.Profile> GetProfileAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO profileDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEditeProfileContractChannel : PresentationLayer.ProfileService.ICreateEditeProfileContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEditeProfileContractClient : System.ServiceModel.ClientBase<PresentationLayer.ProfileService.ICreateEditeProfileContract>, PresentationLayer.ProfileService.ICreateEditeProfileContract {
        
        public CreateEditeProfileContractClient() {
        }
        
        public CreateEditeProfileContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEditeProfileContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeProfileContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeProfileContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddProfile(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO newProfile) {
            base.Channel.AddProfile(newProfile);
        }
        
        public System.Threading.Tasks.Task AddProfileAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO newProfile) {
            return base.Channel.AddProfileAsync(newProfile);
        }
        
        public void EditeProfile(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO editeProfile1) {
            base.Channel.EditeProfile(editeProfile1);
        }
        
        public System.Threading.Tasks.Task EditeProfileAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO editeProfile) {
            return base.Channel.EditeProfileAsync(editeProfile);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO GetProfileDTO(DataAccessLayer.cs.Models.Profile profile) {
            return base.Channel.GetProfileDTO(profile);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO> GetProfileDTOAsync(DataAccessLayer.cs.Models.Profile profile) {
            return base.Channel.GetProfileDTOAsync(profile);
        }
        
        public DataAccessLayer.cs.Models.Profile GetProfile(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO profileDTO) {
            return base.Channel.GetProfile(profileDTO);
        }
        
        public System.Threading.Tasks.Task<DataAccessLayer.cs.Models.Profile> GetProfileAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ProfileDTO profileDTO) {
            return base.Channel.GetProfileAsync(profileDTO);
        }
    }
}
