//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.CardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CardService.ICreateEditeCardContract")]
    public interface ICreateEditeCardContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/CreateCard", ReplyAction="http://tempuri.org/ICreateEditeCardContract/CreateCardResponse")]
        void CreateCard(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO newCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/CreateCard", ReplyAction="http://tempuri.org/ICreateEditeCardContract/CreateCardResponse")]
        System.Threading.Tasks.Task CreateCardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO newCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/EditeCard", ReplyAction="http://tempuri.org/ICreateEditeCardContract/EditeCardResponse")]
        void EditeCard(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO editCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/EditeCard", ReplyAction="http://tempuri.org/ICreateEditeCardContract/EditeCardResponse")]
        System.Threading.Tasks.Task EditeCardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO editCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/DeleteCard", ReplyAction="http://tempuri.org/ICreateEditeCardContract/DeleteCardResponse")]
        void DeleteCard([System.ServiceModel.MessageParameterAttribute(Name="deleteCard")] WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO deleteCard1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/DeleteCard", ReplyAction="http://tempuri.org/ICreateEditeCardContract/DeleteCardResponse")]
        System.Threading.Tasks.Task DeleteCardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO deleteCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/GetAllColumnCards", ReplyAction="http://tempuri.org/ICreateEditeCardContract/GetAllColumnCardsResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[] GetAllColumnCards(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/GetAllColumnCards", ReplyAction="http://tempuri.org/ICreateEditeCardContract/GetAllColumnCardsResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[]> GetAllColumnCardsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/GetAllCardsIncludeAttach", ReplyAction="http://tempuri.org/ICreateEditeCardContract/GetAllCardsIncludeAttachResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[] GetAllCardsIncludeAttach(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeCardContract/GetAllCardsIncludeAttach", ReplyAction="http://tempuri.org/ICreateEditeCardContract/GetAllCardsIncludeAttachResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[]> GetAllCardsIncludeAttachAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEditeCardContractChannel : PresentationLayer.CardService.ICreateEditeCardContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEditeCardContractClient : System.ServiceModel.ClientBase<PresentationLayer.CardService.ICreateEditeCardContract>, PresentationLayer.CardService.ICreateEditeCardContract {
        
        public CreateEditeCardContractClient() {
        }
        
        public CreateEditeCardContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEditeCardContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeCardContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeCardContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateCard(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO newCard) {
            base.Channel.CreateCard(newCard);
        }
        
        public System.Threading.Tasks.Task CreateCardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO newCard) {
            return base.Channel.CreateCardAsync(newCard);
        }
        
        public void EditeCard(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO editCard) {
            base.Channel.EditeCard(editCard);
        }
        
        public System.Threading.Tasks.Task EditeCardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO editCard) {
            return base.Channel.EditeCardAsync(editCard);
        }
        
        public void DeleteCard(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO deleteCard1) {
            base.Channel.DeleteCard(deleteCard1);
        }
        
        public System.Threading.Tasks.Task DeleteCardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO deleteCard) {
            return base.Channel.DeleteCardAsync(deleteCard);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[] GetAllColumnCards(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column) {
            return base.Channel.GetAllColumnCards(column);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[]> GetAllColumnCardsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column) {
            return base.Channel.GetAllColumnCardsAsync(column);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[] GetAllCardsIncludeAttach(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column) {
            return base.Channel.GetAllCardsIncludeAttach(column);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.CardDTO[]> GetAllCardsIncludeAttachAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO column) {
            return base.Channel.GetAllCardsIncludeAttachAsync(column);
        }
    }
}
