//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.ColumnService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ColumnService.ICreateEditColumnsContract")]
    public interface ICreateEditColumnsContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/AddNewColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/AddNewColumnResponse")]
        void AddNewColumn(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO newColumn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/AddNewColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/AddNewColumnResponse")]
        System.Threading.Tasks.Task AddNewColumnAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO newColumn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/EditeColumnName", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/EditeColumnNameResponse")]
        void EditeColumnName(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO editColumn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/EditeColumnName", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/EditeColumnNameResponse")]
        System.Threading.Tasks.Task EditeColumnNameAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO editColumn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/DeleteColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/DeleteColumnResponse")]
        void DeleteColumn([System.ServiceModel.MessageParameterAttribute(Name="deleteColumn")] WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO deleteColumn1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/DeleteColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/DeleteColumnResponse")]
        System.Threading.Tasks.Task DeleteColumnAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO deleteColumn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/GetColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/GetColumnResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO GetColumn(DataAccessLayer.cs.Models.Column column);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/GetColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/GetColumnResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO> GetColumnAsync(DataAccessLayer.cs.Models.Column column);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/GetUserColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/GetUserColumnResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[] GetUserColumn(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/GetUserColumn", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/GetUserColumnResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[]> GetUserColumnAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/GetUserColumnIncludeCards", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/GetUserColumnIncludeCardsResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[] GetUserColumnIncludeCards(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditColumnsContract/GetUserColumnIncludeCards", ReplyAction="http://tempuri.org/ICreateEditColumnsContract/GetUserColumnIncludeCardsResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[]> GetUserColumnIncludeCardsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEditColumnsContractChannel : PresentationLayer.ColumnService.ICreateEditColumnsContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEditColumnsContractClient : System.ServiceModel.ClientBase<PresentationLayer.ColumnService.ICreateEditColumnsContract>, PresentationLayer.ColumnService.ICreateEditColumnsContract {
        
        public CreateEditColumnsContractClient() {
        }
        
        public CreateEditColumnsContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEditColumnsContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditColumnsContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditColumnsContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddNewColumn(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO newColumn) {
            base.Channel.AddNewColumn(newColumn);
        }
        
        public System.Threading.Tasks.Task AddNewColumnAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO newColumn) {
            return base.Channel.AddNewColumnAsync(newColumn);
        }
        
        public void EditeColumnName(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO editColumn) {
            base.Channel.EditeColumnName(editColumn);
        }
        
        public System.Threading.Tasks.Task EditeColumnNameAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO editColumn) {
            return base.Channel.EditeColumnNameAsync(editColumn);
        }
        
        public void DeleteColumn(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO deleteColumn1) {
            base.Channel.DeleteColumn(deleteColumn1);
        }
        
        public System.Threading.Tasks.Task DeleteColumnAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO deleteColumn) {
            return base.Channel.DeleteColumnAsync(deleteColumn);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO GetColumn(DataAccessLayer.cs.Models.Column column) {
            return base.Channel.GetColumn(column);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO> GetColumnAsync(DataAccessLayer.cs.Models.Column column) {
            return base.Channel.GetColumnAsync(column);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[] GetUserColumn(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard) {
            return base.Channel.GetUserColumn(userBoard);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[]> GetUserColumnAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard) {
            return base.Channel.GetUserColumnAsync(userBoard);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[] GetUserColumnIncludeCards(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard) {
            return base.Channel.GetUserColumnIncludeCards(userBoard);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.ColumnDTO[]> GetUserColumnIncludeCardsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO userBoard) {
            return base.Channel.GetUserColumnIncludeCardsAsync(userBoard);
        }
    }
}
