//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.BoardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoardService.ICreateEditeBoardContract")]
    public interface ICreateEditeBoardContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/CreateBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/CreateBoardResponse")]
        void CreateBoard(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO newBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/CreateBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/CreateBoardResponse")]
        System.Threading.Tasks.Task CreateBoardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO newBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/DeleteBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/DeleteBoardResponse")]
        void DeleteBoard([System.ServiceModel.MessageParameterAttribute(Name="deleteBoard")] WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO deleteBoard1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/DeleteBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/DeleteBoardResponse")]
        System.Threading.Tasks.Task DeleteBoardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO deleteBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/EditeBoardName", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/EditeBoardNameResponse")]
        void EditeBoardName(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO editBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/EditeBoardName", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/EditeBoardNameResponse")]
        System.Threading.Tasks.Task EditeBoardNameAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO editBoard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoards", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoardsResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[] GetAllUsersBoards(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoards", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoardsResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[]> GetAllUsersBoardsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetBoardResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO GetBoard(DataAccessLayer.cs.Models.Board board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetBoardResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO> GetBoardAsync(DataAccessLayer.cs.Models.Board board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoardsIncludColumns", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoardsIncludColumnsRespon" +
            "se")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[] GetAllUsersBoardsIncludColumns(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoardsIncludColumns", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetAllUsersBoardsIncludColumnsRespon" +
            "se")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[]> GetAllUsersBoardsIncludColumnsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetCurrentUserBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetCurrentUserBoardResponse")]
        WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO GetCurrentUserBoard(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO currUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeBoardContract/GetCurrentUserBoard", ReplyAction="http://tempuri.org/ICreateEditeBoardContract/GetCurrentUserBoardResponse")]
        System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO> GetCurrentUserBoardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO currUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEditeBoardContractChannel : PresentationLayer.BoardService.ICreateEditeBoardContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEditeBoardContractClient : System.ServiceModel.ClientBase<PresentationLayer.BoardService.ICreateEditeBoardContract>, PresentationLayer.BoardService.ICreateEditeBoardContract {
        
        public CreateEditeBoardContractClient() {
        }
        
        public CreateEditeBoardContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEditeBoardContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeBoardContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeBoardContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateBoard(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO newBoard) {
            base.Channel.CreateBoard(newBoard);
        }
        
        public System.Threading.Tasks.Task CreateBoardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO newBoard) {
            return base.Channel.CreateBoardAsync(newBoard);
        }
        
        public void DeleteBoard(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO deleteBoard1) {
            base.Channel.DeleteBoard(deleteBoard1);
        }
        
        public System.Threading.Tasks.Task DeleteBoardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO deleteBoard) {
            return base.Channel.DeleteBoardAsync(deleteBoard);
        }
        
        public void EditeBoardName(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO editBoard) {
            base.Channel.EditeBoardName(editBoard);
        }
        
        public System.Threading.Tasks.Task EditeBoardNameAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO editBoard) {
            return base.Channel.EditeBoardNameAsync(editBoard);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[] GetAllUsersBoards(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam) {
            return base.Channel.GetAllUsersBoards(userTeam);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[]> GetAllUsersBoardsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam) {
            return base.Channel.GetAllUsersBoardsAsync(userTeam);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO GetBoard(DataAccessLayer.cs.Models.Board board) {
            return base.Channel.GetBoard(board);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO> GetBoardAsync(DataAccessLayer.cs.Models.Board board) {
            return base.Channel.GetBoardAsync(board);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[] GetAllUsersBoardsIncludColumns(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam) {
            return base.Channel.GetAllUsersBoardsIncludColumns(userTeam);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO[]> GetAllUsersBoardsIncludColumnsAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.TeamDTO userTeam) {
            return base.Channel.GetAllUsersBoardsIncludColumnsAsync(userTeam);
        }
        
        public WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO GetCurrentUserBoard(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO currUser) {
            return base.Channel.GetCurrentUserBoard(currUser);
        }
        
        public System.Threading.Tasks.Task<WcfBussinesLogicLayerLibrary.ModelsDTO.BoardDTO> GetCurrentUserBoardAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO currUser) {
            return base.Channel.GetCurrentUserBoardAsync(currUser);
        }
    }
}
