//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.ICreateEditeUserContract")]
    public interface ICreateEditeUserContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeUserContract/AddUser", ReplyAction="http://tempuri.org/ICreateEditeUserContract/AddUserResponse")]
        void AddUser(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeUserContract/AddUser", ReplyAction="http://tempuri.org/ICreateEditeUserContract/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeUserContract/DeleteUser", ReplyAction="http://tempuri.org/ICreateEditeUserContract/DeleteUserResponse")]
        void DeleteUser([System.ServiceModel.MessageParameterAttribute(Name="deleteUser")] WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO deleteUser1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeUserContract/DeleteUser", ReplyAction="http://tempuri.org/ICreateEditeUserContract/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO deleteUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeUserContract/EditeUser", ReplyAction="http://tempuri.org/ICreateEditeUserContract/EditeUserResponse")]
        void EditeUser([System.ServiceModel.MessageParameterAttribute(Name="editeUser")] WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO editeUser1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreateEditeUserContract/EditeUser", ReplyAction="http://tempuri.org/ICreateEditeUserContract/EditeUserResponse")]
        System.Threading.Tasks.Task EditeUserAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO editeUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreateEditeUserContractChannel : PresentationLayer.UserService.ICreateEditeUserContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateEditeUserContractClient : System.ServiceModel.ClientBase<PresentationLayer.UserService.ICreateEditeUserContract>, PresentationLayer.UserService.ICreateEditeUserContract {
        
        public CreateEditeUserContractClient() {
        }
        
        public CreateEditeUserContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreateEditeUserContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeUserContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreateEditeUserContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddUser(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO newUser) {
            base.Channel.AddUser(newUser);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO newUser) {
            return base.Channel.AddUserAsync(newUser);
        }
        
        public void DeleteUser(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO deleteUser1) {
            base.Channel.DeleteUser(deleteUser1);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO deleteUser) {
            return base.Channel.DeleteUserAsync(deleteUser);
        }
        
        public void EditeUser(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO editeUser1) {
            base.Channel.EditeUser(editeUser1);
        }
        
        public System.Threading.Tasks.Task EditeUserAsync(WcfBussinesLogicLayerLibrary.ModelsDTO.UserDTO editeUser) {
            return base.Channel.EditeUserAsync(editeUser);
        }
    }
}
