//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClientConsole.LogOnServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogOnServiceReference.ILogOnUserContract")]
    public interface ILogOnUserContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogOnUserContract/CheckCredationals", ReplyAction="http://tempuri.org/ILogOnUserContract/CheckCredationalsResponse")]
        bool CheckCredationals(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogOnUserContract/CheckCredationals", ReplyAction="http://tempuri.org/ILogOnUserContract/CheckCredationalsResponse")]
        System.Threading.Tasks.Task<bool> CheckCredationalsAsync(string login, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogOnUserContractChannel : TestClientConsole.LogOnServiceReference.ILogOnUserContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogOnUserContractClient : System.ServiceModel.ClientBase<TestClientConsole.LogOnServiceReference.ILogOnUserContract>, TestClientConsole.LogOnServiceReference.ILogOnUserContract {
        
        public LogOnUserContractClient() {
        }
        
        public LogOnUserContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogOnUserContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogOnUserContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogOnUserContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckCredationals(string login, string pass) {
            return base.Channel.CheckCredationals(login, pass);
        }
        
        public System.Threading.Tasks.Task<bool> CheckCredationalsAsync(string login, string pass) {
            return base.Channel.CheckCredationalsAsync(login, pass);
        }
    }
}
