//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer.LogService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogService.ILogONContract")]
    public interface ILogONContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogONContract/CheckCredationals", ReplyAction="http://tempuri.org/ILogONContract/CheckCredationalsResponse")]
        WCFBusinesLayer.DTOModel.UserDTO CheckCredationals(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogONContract/CheckCredationals", ReplyAction="http://tempuri.org/ILogONContract/CheckCredationalsResponse")]
        System.Threading.Tasks.Task<WCFBusinesLayer.DTOModel.UserDTO> CheckCredationalsAsync(string login, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogONContractChannel : PresentationLayer.LogService.ILogONContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogONContractClient : System.ServiceModel.ClientBase<PresentationLayer.LogService.ILogONContract>, PresentationLayer.LogService.ILogONContract {
        
        public LogONContractClient() {
        }
        
        public LogONContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogONContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogONContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogONContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFBusinesLayer.DTOModel.UserDTO CheckCredationals(string login, string pass) {
            return base.Channel.CheckCredationals(login, pass);
        }
        
        public System.Threading.Tasks.Task<WCFBusinesLayer.DTOModel.UserDTO> CheckCredationalsAsync(string login, string pass) {
            return base.Channel.CheckCredationalsAsync(login, pass);
        }
    }
}
