// <auto-generated />
namespace DataAccessLayer.cs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Nullabledate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nullabledate));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011627254_Nullable date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
